services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - siscarim

  db:
    container_name: db
    image: postgres:15
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    networks:
      - siscarim
    environment:
      - POSTGRES_DB=siscarim
      - POSTGRES_USER=siscarim
      - POSTGRES_PASSWORD=siscarim123

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8080
    networks:
      - siscarim
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=siscarim
      - DB_USER=siscarim
      - DB_PASSWORD=siscarim123
      - CORS_ORIGIN=http://localhost:8080
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/scripts:/app/scripts:ro

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    expose:
      - 3000
    networks:
      - siscarim
    environment:
      - REACT_APP_API_URL=/api
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  siscarim:
    driver: bridge
