version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15
    restart: always
    env_file:
      - .env
    expose:
      - 5433
    ports:
      - 5433:5433
    networks:
      - siscarim
    environment:
      - POSTGRES_DB=siscarim
      - POSTGRES_USER=siscarim
      - POSTGRES_PASSWORD=siscarim123

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - siscarim
    environment:
      - DB_HOST=db
      - DB_PORT=5433
      - DB_NAME=siscarim
      - DB_USER=siscarim
      - DB_PASSWORD=siscarim123

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - siscarim
    environment:
      - REACT_APP_API_URL=http://backend:8080  # URL do backend para o frontend

networks:
  siscarim:
    driver: bridge
